[project]
name = "zendesk-mcp-server"
version = "0.1.0"
description = "A model context protocol server for Zendesk"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.1.2",
]
